import turtle as trtl

painter = trtl.Turtle()

print("COMPREHENDED, WRITTEN, AND FINALIZED BY DAVID")
painter.pencolor("red")
painter.forward(100)
painter.right(90)
painter.pencolor("blue")
painter.circle(-100)
painter.circle(-50)
painter.pencolor("red")
painter.forward(100)
painter.right(90)
painter.pencolor("blue")
painter.circle(-100)
painter.circle(-50)
painter.pencolor("red")
painter.forward(100)
painter.right(90)
painter.pencolor("blue")
painter.circle(-100)
painter.circle(-50)
painter.pencolor("red")
painter.forward(100)
painter.right(90)
painter.pencolor("blue")
painter.circle(-100)
painter.circle(-50)
painter.pencolor("red")
##COMPREHENDED, WRITTEN, AND FINALIZED BY DAVID

 
wn = trtl.Screen()
wn.mainloop()
