import turtle as trtl

painter = trtl.Turtle()

painter.pencolor("red")
painter.forward(100)
painter.right(90)
painter.pencolor("blue")
painter.circle(-100)
painter.circle(-50)
painter.pencolor("red")
painter.forward(100)
painter.right(90)
painter.pencolor("blue")
painter.circle(-100)
painter.circle(-50)
painter.pencolor("red")
painter.forward(100)
painter.right(90)
painter.pencolor("blue")
painter.circle(-100)
painter.circle(-50)
painter.pencolor("red")
painter.forward(100)
painter.right(90)
painter.pencolor("blue")
painter.circle(-100)
painter.circle(-50)
painter.pencolor("red")

 
wn = trtl.Screen()
wn.mainloop()